name: workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        file: ./coverage.xml
        flags: unittests 
        name: codecov-umbrella 
        fail_ci_if_error: true 
