# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload coverage to Codecov  
      uses: ./
      with:
        #commenting out token because tokenless uploads are now supported
        token: d3c838e3-e5df-44ce-a498-c73044b333d1
        flags: unittest
        name: codecov-1
