# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

name: Maven Package

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
        
    - uses: actions/cache@v1   
      with:
        path: ~/.m2/repository  
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package
    
    - name: Save result
      uses: actions/upload-artifact@v1
      with:
        name: build-result
        path: target
    
  package-jar:
      needs: build
      
      runs-on: ubuntu-latest
      
      steps:

      - uses: actions/checkout@v2

      - name: Load result
        uses: actions/download-artifact@v1
        with:
          name: build-result
          path: target

      # Setup version 12 of Java
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12


      - name: Publish jar to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISTRIBUTION_ID: github
          DISTRIBUTION_NAME: Notes Example Project
          DISTRIBUTION_URL: https://maven.pkg.github.com/${{ github.repository }}
      
    
